import type { Metadata } from "next";
import { DM_Sans, Geist, Geist_Mono, Lora } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"

const lora = Lora({
  subsets : ["latin"],
  weight : ["400","500"],
  style : ["normal","italic"],
  variable : "--font-serif"
});

const dmSans = DM_Sans({
  subsets : ["latin"],
  weight : ["400","500","600","300"],
  variable : "--font-sans"
});


export const metadata: Metadata = {
  title: "resume-analyzer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${lora.variable} ${dmSans.variable} font-sans`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <main className="min-h-screen">
          {/* <Header/> */}
          {children}
        </main>
        {/* <Footer/> */}
        </ThemeProvider> 
      </body>
    </html>
  );
}
