import type { Metadata } from "next";
import { DM_Sans, Geist, Geist_Mono, Lora } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import Footer from "@/components/footer";
import { Header } from "@/components/Header";
import AuthProvider from '../components/sessionProvider';
const lora = Lora({
  subsets : ["latin"],
  weight : ["400","500"],
  style : ["normal","italic"],
  variable : "--font-serif"
});

const dmSans = DM_Sans({
  subsets : ["latin"],
  weight : ["400","500","600","300"],
  variable : "--font-sans"
});


export const metadata: Metadata = {
  title: "resume-analyzer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${lora.variable} ${dmSans.variable} font-sans`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
      <AuthProvider>
        <main className="min-h-screen bg-black">
          <Header/>
          {children}
        </main>
        <Footer/>
      </AuthProvider>
      </body>
    </html>
  );
}
